### ISSUE TITLE
Create a -lts branch to support a wider range of PHP versions

### ISSUE THREAD

**Issue by atomiix** [laminas/laminas-code#115]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Hi,

At PrestaShop we are trying to provide a wide range of PHP versions for our next version, which would be from PHP 7.2 to PHP 8.1.

Even if with multiple versions of laminas-code, that range can be covered, there is no unique version that can do it.

Would it be possible to consider creating a 4.5.x-lts branch that would cover PHP versions from 7.2 to 8.1? We already created a [repo](https://github.com/PrestaShop/laminas-code-lts) that does that on PrestaShop's organisation but we think that it would make sense to have a dedicated branch on the original project. We would be happy to contribute, of course!

Let me know if you would be interested or if you want to discuss the solution :)

**Comment by Ocramius** [comment]
Heyo,

It is not realistically feasible to support wider dependency ranges for maintainers (and availability them of) of the repo:
 * `4.0.0` onwards supports PHP 7.4+
 * I certainly accept patches for `laminas/code:3.0.0` onwards, where `php:5.5` is still supported (for security issues only, nothing else).

The only alternative is to have regular funding to deal with that, and introduce at least 4~5 full days of work for this repository a month, at which point dedicated maintenance would occur.

Further reading on that:

 * https://github.com/laminas/technical-steering-committee/blob/8a8a30f933916a435a788f07705c5f75c71073d8/meetings/minutes/2020-03-02-TSC-Minutes.md#lts-policy
 * (unofficial, I just happen to be the maintainer for this specific repo) https://github.com/Ocramius/.github/blob/6d4561515513f6d59fb144d838971d4a7715e3e4/version-support.md#dependency-upgrades

Overall, the community should move forward, and prioritize **MOVING AWAY** from PHP 7.3 and earlier, which goes EOL in 2 weeks, according to https://www.php.net/supported-versions.php

PHP 8.1 support will come with `4.5.0`, and `4.6.0` will likely drop PHP 7.4 support, in order to allow for further internal refactoring.

**Comment by atomiix** [comment]
I certainly understand your point of view but in the CMS ecosystem, php versions can be slow to upgrade, that's why we had to try ;)

I'm closing this issue as nothing will be done on this repository.

**Comment by Ocramius** [comment]
@atomiix it's also impedance between companies and "weekend warriors".

More context on that in https://github.com/Ocramius/.github/blob/6d4561515513f6d59fb144d838971d4a7715e3e4/why-i-do-open-source.md

I would certainly consider widening ranges if I had dedicated paid time to do it, and that would effectively turn it into "client work", but as it is something I do over the weekends, it is not in my interest to make it even harder (and harder to improve the codebase).

**Comment by eternoendless** [comment]
Just to clarify - @atomiix didn't ask _you_ to do it, but asked if _we_ could do it together in the original repository, because to us it makes sense to collaborate on open source software instead of forking away and going solo. Of course, you're free to think differently.

**Comment by Ocramius** [comment]
Yes, but the maintenance still ends up here, hence there's no difference.

**Comment by eternoendless** [comment]
We're willing to collaborate on that if you are.

**Comment by Ocramius** [comment]
As I mentioned above, I'm not willing to cooperate on including further maintenance effort: conditions have been explained clearly on a [previous comment](https://github.com/laminas/laminas-code/issues/115#issuecomment-977731791), so it really a financing problem.

**Comment by eternoendless** [comment]
I hear you loud and clear.

In case anyone else is interested, we have forked the library here in order to provide the wide compatibility range we needed: https://github.com/PrestaShop/laminas-code-lts
