### ISSUE TITLE
Case sensitive method name

### ISSUE THREAD

**Issue by tomasz-kusy** [laminas/laminas-code#41]
Hi,
In PHP method names are case sensitive. Why you don't allow to generate case sensitive method names?
I'm using https://github.com/goetas-webservices/xsd2php to generate classes. I've got a issue with same xml attribute name (id and ID). Unfortunately I can't fix it because method 'hasMethod' is not case sensitive.

**Comment by michalbundyra** [comment]
@tomasz-kusy Thanks for reporting.
I would consider it as a bug. Would you be able to provide a fix with tests? Thanks!

**Comment by weierophinney** [comment]
@tomasz-kusy I'm confused, because you're saying PHP method names are case sensitive, and then asking why we don't allow generating case sensitive method names, and then indicate that `hasMethod` is not case sensitive. I think one or more of those is either a request or an assertion of case **in**sensitive.

To my knowledge, based on the published documentation and looking at the code, we use _exactly_ the case provided to us, which means that users must call those methods using exactly that same case. As an example, if you call a method you are generating `hasMethod`, users will need to call it using the same case: `$instance->hasMethod()`. 

From what I can tell of your description, the issue arises because you have two XML attributes for the same element that use _different_ case: "id" and "ID", which are being used to create two different methods.

The problem here is that while PHP treats method names as case sensitive for purposes of _invocation_, it treats them as case **in**sensitive for purposes of _definition_. Try the following:

```php
class Test
{
    public function getID(): string
    {
        return __METHOD__;
    }

    public function getid(): string
    {
        return __METHOD__;
    }
}
```

This results in a fatal error: "Cannot redeclare Test::getid()".

As such, this is not something we can fix; the language simply does not allow it.

If your problem is different, please let us know.

**Comment by tomasz-kusy** [comment]
You're right! 
Because class properties are case sensitive I (wrongly) assumed that method names are too. My fault :-/
A man learns his whole life...
Closing issue.
